version: "3.9"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/nginx.dockerfile
        ports:
            - "80:80"
        links:
            - fpm
        volumes:
            - ./:/var/www/html
    fpm:
        build:
            context: .
            dockerfile: docker/fpm.dockerfile
        volumes:
            - ./:/var/www/html
            - ./storage/app/:/var/www/html/storage/app
            - ./storage/app/public/:/var/www/html/storage/app/public
            - ./docker/php/ext-php.ini:/usr/local/etc/php/conf.d/docker-php-ext-php.ini
            - ./docker/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        links:
            - mysql
    mysql:
        image: mysql:5.7
        ports:
            - "33061:3306"
        environment:
            - MYSQL_ROOL_PASSWORD=root
            - MYSQL_DATABASE=cyberzilla
            - MYSQL_ROOT_PASSWORD=root

